version: '3.8'

services:
  server_a:
    build:
      context: ./server_a
    ports:
      - "5000:5000"  # Opcjonalnie wystawiamy port na zewnątrz

  server_b:
    build:
      context: ./server_b
    ports:
      - "5000:5000"  # Opcjonalnie wystawiamy port na zewnątrz

  main_server:
    build:
      context: ./main_server
    ports:
      - "5000:5000"  # Główny serwer widoczny na porcie 5000
    depends_on:
      - server_a
      - server_b
