version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: flask_server
    ports:
      - "5000:5000"
    networks:
      - app_network

  client:
    build:
      context: ./client
    container_name: data_client
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
